SELECT USERID, SERVICETYPE, PLANNAME, 
            CASE 
                WHEN SERVICETYPE='POTS' THEN (SELECT LISTAGG(PHONENO, ', ') WITHIN GROUP (ORDER BY PHONENO) AS SUBJECTS FROM PHONEALLOCATION WHERE USERID='ijsisb' AND STATUS='ALLOCATED')
                ELSE NULL
                END AS DETAIL
            FROM USERPLANS WHERE USERID='ijsisb';
            
            
            SELECT INF.ID,INF.USERID,INF.TEAM_NAME,INF.OPERATOR,P.OFFICECITY,INF.CUSTOMER_TYPE,INF.STATUS,INF.DATETIME
                ,INF.NTLNO
                FROM INSTALLATION_FORM INF 
                LEFT JOIN PROFESSIONALINFO P ON  P.TEAMSHORTTEXT = INF.TEAM_NAME 
                WHERE P.OFFICECITY='Islamabad' AND INF.DATETIME >= TO_DATE('01-AUG-2023', 'DD-MON-YYYY HH24:MI:SS') AND 
                INF.DATETIME <= TO_DATE('29-NOV-2023', 'DD-MON-YYYY HH24:MI:SS')
                GROUP BY INF.ID,INF.USERID,INF.TEAM_NAME,INF.OPERATOR,P.OFFICECITY,INF.CUSTOMER_TYPE,INF.STATUS,INF.DATETIME,INF.NTLNO;
                
            SELECT INF.ID, INF.USERID, INF.TEAM_NAME, INF.OPERATOR, P.OFFICECITY, INF.CUSTOMER_TYPE, INF.STATUS, INF.DATETIME
               ,INF.NTLNO
               FROM INSTALLATION_FORM INF 
               LEFT JOIN PROFESSIONALINFO P ON P.TEAMSHORTTEXT = INF.TEAM_NAME 
               WHERE P.OFFICECITY='Islamabad' AND INF.DATETIME >= TO_DATE('01-08-2023', 'DD-MM-YYYY HH24:MI:SS') AND 
               INF.DATETIME <= TO_DATE('29-11-2023', 'DD-MM-YYYY HH24:MI:SS')
               GROUP BY INF.ID, INF.USERID, INF.TEAM_NAME, INF.OPERATOR, P.OFFICECITY, INF.CUSTOMER_TYPE, INF.STATUS, INF.DATETIME, INF.NTLNO;
               
               
               
SELECT 
* FROM professionalinfo ;



  select * from (
            select EID, TTID, 
            (SELECT TEAMSHORTTEXT FROM professionalinfo where empid = OTP_VERIFIEDBY) as teamofemployee,
            (SELECT OFFICECITY FROM professionalinfo where empid = OTP_VERIFIEDBY) as EMP_OFFICECITY,
            (SELECT count(ttid) as totaltt FROM ntlcrm.etickets where OPERATOR = OTP_VERIFIEDBY and status = 'Form_Created') as totaltt,
            FAULTTYPE, SUBFAULTTYPE,SECTOR,  OTP_VERIFIEDBY, DATETIME from (
            SELECT 
                ed.eid, TTID,
                TT.FAULTTYPE, TT.SUBFAULTTYPE,TT.SECTOR,
                MAX(CASE WHEN pc.key = 'OTP VERIFICATION' THEN pc.OPERATOR END) AS OTP_VERIFIEDBY,
               max(ed.datetime) as datetime
               FROM ntlcrm.etickets e
               JOIN ntlcrm.eticketdetail ed ON e.id = ed.eid 
               join form_actions pc on pc.eid = e.id
               JOIN installed_hardware hd on e.id = hd.EFORM_ID
               join ntlcrm.troubleticket tt on  tt.id = e.ttid
               WHERE e.status = 'Form_Created' AND ed.status = 'Form_Created' 
               and hd.status = 'Form_Created' 
               GROUP BY  ed.eid,e.ttid, ed.status,
               TTID,
               TT.FAULTTYPE, TT.SUBFAULTTYPE,TT.SECTOR
              ))    
             WHERE DATETIME >= TO_DATE('29-AUG-2023 00:00:00', 'DD-MON-YYYY HH24:MI:SS')
               AND DATETIME <= TO_DATE('29-NOV-2023 23:59:59', 'DD-MON-YYYY HH24:MI:SS');


SELECT A.ORGANIZATIONALUNIT, A.TEAMSHORTTEXT ,A.TEAM_CITY, B.INSTALLATIONS,C.FIBER_CIRCULAR,C.FIBER_STANDARD,C.FIBER_CIRCULAR_INSIDE,C.FIBER_STANDARD_INSIDE,C.FIBER_CIRCULAR_OUTSIDE,C.FIBER_STANDARD_OUTSIDE,
    C.CIVIL_CHARGES_TEAM,C.NO_OF_SPLICES_TEAM,C.MINI_BPR_IN,C.MINI_BPR_OUT,C.PVCPIPE_1_IN,C.PVCPIPE_1_OUT,C.PVCPIPE_3BY4_IN,C.PVCPIPE_3BY4_OUT,C.PVCFLEXPIPE_1POINT25_IN,C.PVCFLEXPIPE_1POINT25_OUT,C.PVCFLEXPIPE_0POINT5_IN,C.PVCFLEXPIPE_0POINT5_OUT,C.STEELFLEXPIPE_0POINT5_IN,C.STEELFLEXPIPE_0POINT5_OUT,C.STEELFLEXPIPE_1POINT25_IN,
    C.STEELFLEXPIPE_1POINT25_OUT,B.TOTAL,
    C.DURADUCT_16BY25_TEAM_IN,C.DURADUCT_16BY25_TEAM_OUT,C.DURADUCT_25BY25_TEAM_IN,C.DURADUCT_25BY25_TEAM_OUT,C.UTP_CABLE_TEAM,C.CONNECTOR_RJ45_TEAM,C.CABLE_RG6_TEAM,C.SPLITTER_2_TEAM,C.SPLITTER_3_TEAM, C.SPLITTER_4_TEAM,C.DURADUCT_16BY16_TEAM_IN,C.DURADUCT_16BY16_TEAM_OUT,
    C.DURADUCT_40BY40_TEAM_IN, C.DURADUCT_40BY40_TEAM_OUT,C.CONNECTOR_IEC_TEAM,C.JOINTER_RF_TEAM,C.COLDPRESS_TEAM,C.ATTENUATOR_TEAM,C.UTP_CABLE_2PAIR_TEAM,C.CABLE_RJ11_TEAM,C.TELEPHONE_ROZETTE_TEAM,C.ETHERNET_BOOT_TEAM,
    C.CONNECTOR_RJ7_TEAM,C.PIPEANDDUCT_LAYING_TEAM,C.CABLE_LAYING_TEAM,C.ETHERNET_JOINTER_TEAM,C.ROUTERS_TEAM,C.HD_BOX_TEAM,c.STB_TEAM,C.AMPLIFIER_TEAM_IN,C.AMPLIFIER_TEAM_OUT,C.ATA_TEAM_IN,C.ATA_TEAM_OUT,C.CABLE_TRACING_TEAM,C.N_DOCTOR_TEAM,
    C.NWATCH_TEAM,C.ONT_TEAM,C.UPS_TEAM,D.SPLICE_NAP_ODF_TEAM,D.SPLICE_IN_DC_TEAM,C.VISIT_CHARGES_TEAM,C.SPLICE_CHARGES_TEAM,C.PIPEANDDUCT_CHARGES_TEAM,C.CABLE_CHARGES_TEAM,
    C.CABLE_TRACING_CHARGES,D.ODF_INSTALLED_TEAM,D.ONT_PRE_CONFIGURED_TEAM,D.SERVICE_CHECK_TEAM,D.DRILL_HOLE_TEAM,D.LOGO_PLATE_TEAM,C.IEC_90DEGREES,C.FIBER_CIRCULAR_OUTSIDE+C.FIBER_STANDARD_OUTSIDE AS NAP_TO_FIBER,C.FIBER_CIRCULAR_INSIDE+C.FIBER_STANDARD_INSIDE AS INSIDE_PREMISES,
    C.FIBER_CIRCULAR+C.FIBER_STANDARD AS TOTAL_FIBER,C.CIVIL_CHARGES_TEAM+VISIT_CHARGES_TEAM+C.PIPEANDDUCT_CHARGES_TEAM+C.CABLE_CHARGES_TEAM+C.CABLE_TRACING_CHARGES+C.SPLICE_CHARGES_TEAM AS TOTAL_VAS_CHARGES, C.WAITING,
    C.NAPTOENTRYPOINT,C.INSIDE_PREMISES 
  
    FROM ( SELECT  DISTINCT P.TEAMSHORTTEXT, P.ORGANIZATIONALUNIT,
    CASE 
    WHEN P.ORGANIZATIONALUNIT LIKE '%RWP%' THEN 'Rawalpindi' 
    WHEN P.ORGANIZATIONALUNIT LIKE '%ISB%' THEN 'Islamabad'
    WHEN P.ORGANIZATIONALUNIT LIKE '%FSD%' THEN 'Faislabad'
    WHEN P.ORGANIZATIONALUNIT LIKE '%PSH%' THEN 'Peshawar' END AS TEAM_CITY
    FROM PROFESSIONALINFO P LEFT JOIN INSTALLATION_FORM F
    ON P.TEAMSHORTTEXT = F.TEAM_NAME) A,
   (
   SELECT COUNT(TEAM_NAME) AS INSTALLATIONS, INS.TEAM_NAME,
   NVL(SUM(CASE WHEN INS.GRAND_TOTAL IS NOT NULL THEN INS.GRAND_TOTAL END),0) AS TOTAL
   FROM INSTALLATION_FORM INS
   GROUP BY INS.TEAM_NAME ) B,
  (
   SElECT INS.TEAM_NAME,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Optic Fiber Cable' AND FD.DETAIL_1='FIBER OPTIC CABLE 2F CIRCULAR DROP TYPE' THEN FD.QUANTITY END ),0)AS FIBER_CIRCULAR,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Optic Fiber Cable' AND FD.DETAIL_1='FIBER OPTIC CABLE 2F (CLT TYPE)' THEN FD.QUANTITY END ),0)AS FIBER_STANDARD,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Optic Fiber Cable' AND FD.DETAIL_1='FIBER OPTIC CABLE 2F CIRCULAR DROP TYPE' THEN FD.IN_PREMISES END ),0)AS FIBER_CIRCULAR_INSIDE,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Optic Fiber Cable' AND FD.DETAIL_1='FIBER OPTIC CABLE 2F (CLT TYPE)' THEN FD.IN_PREMISES END ),0)AS FIBER_STANDARD_INSIDE,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Optic Fiber Cable' AND FD.DETAIL_1='FIBER OPTIC CABLE 2F CIRCULAR DROP TYPE' THEN FD.OUT_PREMISES END),0)AS FIBER_CIRCULAR_OUTSIDE,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Optic Fiber Cable' AND FD.DETAIL_1='FIBER OPTIC CABLE 2F (CLT TYPE)' THEN FD.OUT_PREMISES END ),0)AS FIBER_STANDARD_OUTSIDE,
   NVL(SUM(CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Civil Work' THEN FD.PRICE END),0 )AS CIVIL_CHARGES_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Splice Charges' THEN FD.QUANTITY END),0) AS NO_OF_SPLICES_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='OSP Equipment' AND FD.DETAIL_1='JOINT CLOSURE BPR 1X1 GJS-H1102 (BLACK)' OR FD.DETAIL_1='JOINT CLOSURE BPR 1X1 GJS-H1102 (WHITE)' THEN FD.IN_PREMISES END),0) AS MINI_BPR_IN,
      NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='OSP Equipment' AND FD.DETAIL_1='JOINT CLOSURE BPR 1X1 GJS-H1102 (BLACK)' OR FD.DETAIL_1='JOINT CLOSURE BPR 1X1 GJS-H1102 (WHITE)' THEN FD.OUT_PREMISES END),0) AS MINI_BPR_OUT,
   NVL(SUM (CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Team Visit' AND FD.DETAIL_1='SUBSEQUENT WAITING CHARGES OF TEAM' THEN FD.PRICE  END),0) AS WAITING,
   NVL(SUM (CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Optic Fiber Cable' AND FD.DETAIL_1 LIKE 'FIBER OPTIC CABLE 2F %' THEN FD.OUT_PREMISES end ),0) as NAPTOENTRYPOINT,
   NVL(SUM (CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Optic Fiber Cable' AND FD.DETAIL_1 LIKE 'FIBER OPTIC CABLE 2F %' THEN FD.IN_PREMISES end ),0) as INSIDE_PREMISES,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='PVC PIPE 1 INCH' THEN FD.IN_PREMISES END),0) AS PVCPIPE_1_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='PVC PIPE 1 INCH' THEN FD.OUT_PREMISES END),0) AS PVCPIPE_1_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='PVC PIPE 3/4 INCH' THEN FD.IN_PREMISES END),0) AS PVCPIPE_3BY4_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='PVC PIPE 3/4 INCH' THEN FD.OUT_PREMISES END),0) AS PVCPIPE_3BY4_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='PVC PIPE FLEXIBLE 1.25 INCH' THEN FD.IN_PREMISES END),0) AS PVCFLEXPIPE_1POINT25_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='PVC PIPE FLEXIBLE 1.25 INCH' THEN FD.OUT_PREMISES END),0) AS PVCFLEXPIPE_1POINT25_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='PVC PIPE FLEXIBLE 0.50 INCH' then FD.IN_PREMISES END),0) AS PVCFLEXPIPE_0POINT5_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='PVC PIPE FLEXIBLE 0.50 INCH' then FD.OUT_PREMISES END),0) AS PVCFLEXPIPE_0POINT5_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='STEEL FLEXIBLE 0.50 INCH' THEN FD.IN_PREMISES END),0) AS STEELFLEXPIPE_0POINT5_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='STEEL FLEXIBLE 0.50 INCH' THEN FD.OUT_PREMISES END),0) AS STEELFLEXPIPE_0POINT5_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='STEEL FLEXIBLE 1.25 INCH' THEN FD.IN_PREMISES END),0) AS STEELFLEXPIPE_1POINT25_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='STEEL FLEXIBLE 1.25 INCH' THEN FD.OUT_PREMISES END),0) AS STEELFLEXPIPE_1POINT25_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='DURA DUCT 16/25 ADAMJEE' THEN FD.IN_PREMISES END),0) AS DURADUCT_16BY25_TEAM_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='DURA DUCT 16/25 ADAMJEE' THEN FD.OUT_PREMISES END),0) AS DURADUCT_16BY25_TEAM_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='DURA DUCT 25/25 ADAMJEE' THEN FD.IN_PREMISES END),0) AS DURADUCT_25BY25_TEAM_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='DURA DUCT 25/25 ADAMJEE' THEN FD.OUT_PREMISES END),0) AS DURADUCT_25BY25_TEAM_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Cables For Install.' AND FD.DETAIL_1='CABLE CAT-5 4 PAIR' THEN FD.QUANTITY END),0) AS UTP_CABLE_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Installation Cons.' AND FD.DETAIL_1='CONNECTOR RJ-45' THEN FD.QUANTITY END),0) AS CONNECTOR_RJ45_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Cables For Install.' AND FD.DETAIL_1='CABLE RG-6' THEN FD.QUANTITY END),0)AS CABLE_RG6_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Video Items for Inst' AND FD.DETAIL_1='SPLITTER 2-WAY' THEN FD.QUANTITY END),0) AS SPLITTER_2_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Video Items for Inst' AND FD.DETAIL_1='SPLITTER 3-WAY' THEN FD.QUANTITY END),0) AS SPLITTER_3_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Video Items for Inst' AND FD.DETAIL_1='SPLITTER 4-WAY' THEN FD.QUANTITY END),0) AS SPLITTER_4_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='DURA DUCT 16/16 ADAMJEE' THEN FD.IN_PREMISES END),0) AS DURADUCT_16BY16_TEAM_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='DURA DUCT 16/16 ADAMJEE' THEN FD.OUT_PREMISES END),0) AS DURADUCT_16BY16_TEAM_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='DURA DUCT 40/40 ADAMJEE' THEN FD.IN_PREMISES END),0) AS DURADUCT_40BY40_TEAM_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Pipes%Ducting' AND FD.DETAIL_1='DURA DUCT 40/40 ADAMJEE' THEN FD.OUT_PREMISES END),0) AS DURADUCT_40BY40_TEAM_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Video Items for Inst' AND FD.DETAIL_1='CONNECTOR IEC/RF' THEN FD.QUANTITY END),0) AS CONNECTOR_IEC_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Video Items for Inst' AND FD.DETAIL_1='JOINTER - RF' THEN FD.QUANTITY END),0) AS JOINTER_RF_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Video Items for Inst' AND FD.DETAIL_1='CONNECTOR COLD PRESS - F/RG-6' THEN FD.QUANTITY END),0) AS COLDPRESS_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Video Items for Inst' AND FD.DETAIL_1 LIKE '%WAY TAP/ATTENUATOR%' THEN FD.QUANTITY END),0) AS ATTENUATOR_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Cables For Install.' AND FD.DETAIL_1='CABLE CAT-5 2 PAIR' THEN FD.QUANTITY END),0) AS UTP_CABLE_2PAIR_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Cables For Install.' AND FD.DETAIL_1='CABLE RG-11' THEN FD.QUANTITY END),0) AS CABLE_RJ11_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Installation Cons.' AND FD.DETAIL_1='TELEPHONE ROZZETS' THEN FD.QUANTITY END),0) AS TELEPHONE_ROZETTE_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Installation Cons.' AND FD.DETAIL_1='BOOT PROTECTORS FOR RJ-45' THEN FD.QUANTITY END),0) AS ETHERNET_BOOT_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Video Items for Inst' AND FD.DETAIL_1='CONNECTOR RG-7' THEN FD.QUANTITY END),0) AS CONNECTOR_RJ7_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Cable Laying' AND FD.DETAIL_1='CABLE LAYING CHARGES IN DUCT/PIPE' THEN FD.QUANTITY END),0) AS PIPEANDDUCT_LAYING_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Cable Laying' AND FD.DETAIL_1='CABLE LAYING' THEN FD.QUANTITY END),0) AS CABLE_LAYING_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Installation Cons.' AND FD.DETAIL_1='JOINTER ETHERNET' THEN FD.QUANTITY END),0)AS ETHERNET_JOINTER_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Video Items for Inst' and FD.DETAIL_1='CONNECTOR IEC MALE TO FEMALE RIGHT ANGLE' then FD.QUANTITY END),0) AS IEC_90DEGREES,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE LIKE 'Routers%Switches' AND FD.DETAIL_1 LIKE 'ROUTER%' THEN FD.QUANTITY END),0) AS ROUTERS_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Set Top Box' AND FD.DETAIL_1='HD BOX' THEN FD.QUANTITY END),0) AS HD_BOX_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Set Top Box' AND FD.DETAIL_1='SET TOP BOX SUMAVISION' THEN FD.QUANTITY END),0) AS STB_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Misc. H/W For Sale' AND FD.DETAIL_1 LIKE 'AMPLIFIER%' THEN FD.IN_PREMISES END),0) AS AMPLIFIER_TEAM_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Misc. H/W For Sale' AND FD.DETAIL_1 LIKE 'AMPLIFIER%' THEN FD.OUT_PREMISES END),0) AS AMPLIFIER_TEAM_OUT,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Phone Adapters' AND FD.DETAIL_1 LIKE 'ATA%' THEN FD.IN_PREMISES END),0) AS ATA_TEAM_IN,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Phone Adapters' AND FD.DETAIL_1 LIKE 'ATA%' THEN FD.OUT_PREMISES END),0) AS ATA_TEAM_OUT,
   NVL(SUM(CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Cable Tracing' AND FD.DETAIL_1='CABLE TRACING' THEN FD.QUANTITY END),0) AS CABLE_TRACING_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Set Top Box' AND FD.DETAIL_1='HD BOX JOY' THEN FD.QUANTITY END),0) AS N_DOCTOR_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='CONSUMABLE' AND FD.VALUE='Misc. H/W For Sale' AND FD.DETAIL_1='NWATCH SMART BOX H96 PRO PLUS 4K ULTRA' THEN FD.QUANTITY END),0) AS NWATCH_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Team Visit' AND DETAIL_1='TEAM VISIT' THEN FD.PRICE END),0 )AS VISIT_CHARGES_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Splice Charges' THEN FD.PRICE END),0) AS SPLICE_CHARGES_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Cable Laying' AND FD.DETAIL_1='CABLE LAYING CHARGES IN DUCT/PIPE' THEN FD.PRICE END),0) AS PIPEANDDUCT_CHARGES_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Cable Laying' AND FD.DETAIL_1='CABLE LAYING' THEN FD.PRICE END),0) AS CABLE_CHARGES_TEAM,
   NVL(SUM(CASE WHEN FD.KEY='LABOR' AND FD.VALUE='Cable Tracing' AND FD.DETAIL_1='CABLE TRACING' THEN FD.PRICE END),0) AS CABLE_TRACING_CHARGES,
   NVL(COUNT(CASE WHEN IH.HARDWARE_NAME='Huawei ONT' OR IH.HARDWARE_NAME='ONT + UPS'  AND IH.MATERIAL_DESCRIPTION='ONT HUAWEI GPON EG8247H5' THEN IH.MATERIAL_DESCRIPTION END),0) AS ONT_TEAM,
   NVL(COUNT(CASE WHEN HARDWARE_NAME='ONT + UPS' AND MATERIAL_DESCRIPTION='UPS HUAWEI - 50W' THEN MATERIAL_DESCRIPTION END ),0)AS UPS_TEAM
   
   FROM INSTALLATION_FORM INS
   LEFT JOIN FORM_DETAIL FD ON FD.FORM_ID=INS.ID
   LEFT JOIN INSTALLED_HARDWARE IH ON IH.FORM_ID=INS.ID
   WHERE INS.DATETIME >= TO_DATE('29-AUG-2023 00:00:00', 'DD-MON-YYYY HH24:MI:SS') 
   AND INS.DATETIME <= TO_DATE('29-NOV-2023 23:59:59', 'DD-MON-YYYY HH24:MI:SS')
   GROUP BY INS.TEAM_NAME) C LEFT JOIN 
   (
   SELECT  A.TEAM_NAME, SUM(SPLICE_NAP_ODF_TEAM) AS SPLICE_NAP_ODF_TEAM, SUM(SPLICE_IN_DC_TEAM) SPLICE_IN_DC_TEAM, SUM(ODF_INSTALLED_TEAM) ODF_INSTALLED_TEAM, SUM(ONT_PRE_CONFIGURED_TEAM) ONT_PRE_CONFIGURED_TEAM,SUM(SERVICE_CHECK_TEAM) SERVICE_CHECK_TEAM,SUM(DRILL_HOLE_TEAM) DRILL_HOLE_TEAM,SUM(LOGO_PLATE_TEAM) LOGO_PLATE_TEAM FROM (
   SELECT IC.FORM_ID,INF.TEAM_NAME,
   NVL(COUNT(CASE WHEN IC.SPLICE_NAP_ODF='YES' THEN IC.SPLICE_NAP_ODF END ),0) AS SPLICE_NAP_ODF_TEAM,
   NVL(COUNT(CASE WHEN IC.SPLICE_IN_DC='YES' THEN IC.SPLICE_IN_DC END),0) AS SPLICE_IN_DC_TEAM,
   NVL(COUNT(CASE WHEN IC.ODF_INSTALLED='YES' THEN IC.ODF_INSTALLED END),0) AS ODF_INSTALLED_TEAM,
   NVL(COUNT(CASE WHEN IC.ONT_PRE_CONFIGURED='YES' THEN IC.ONT_PRE_CONFIGURED END),0) AS ONT_PRE_CONFIGURED_TEAM,
   NVL(COUNT(CASE WHEN IC.SERVICE_CHECKED='YES' THEN IC.SERVICE_CHECKED END),0) AS SERVICE_CHECK_TEAM,
   NVL(COUNT(CASE WHEN IC.DRILL_HOLE_SEALED='YES' THEN IC.DRILL_HOLE_SEALED END),0) AS DRILL_HOLE_TEAM,
   NVL(COUNT(CASE WHEN IC.LOGO_PLATE_INSTALLED='YES' THEN IC.LOGO_PLATE_INSTALLED END),0) AS LOGO_PLATE_TEAM
   from INSTALLATION_COMPONENTS IC 
   left join INSTALLATION_FORM INF on INF.id=IC.FORM_ID
   group by FORM_ID, INF.TEAM_NAME, IC.FORM_ID) a
   group by  a.TEAM_NAME 
   ) D on D.TEAM_NAME=C.TEAM_NAME
   where a.TEAMSHORTTEXT = B.TEAM_NAME and B.TEAM_NAME=C.TEAM_NAME and a.ORGANIZATIONALUNIT is not null
   order by B.TEAM_NAME;
   
   
   
   
   
   
   
   
   
      SELECT *  FROM (
            SELECT EID, TTID, 
            (SELECT TEAMSHORTTEXT FROM professionalinfo where empid = OTP_VERIFIEDBY) as teamofemployee,
            (SELECT OFFICECITY FROM professionalinfo where empid = OTP_VERIFIEDBY) as EMP_OFFICECITY,
            (SELECT count(ttid) as totaltt FROM ntlcrm.etickets where OPERATOR = OTP_VERIFIEDBY and status = 'Form_Created') as totaltt,
            FAULTTYPE, SUBFAULTTYPE,SECTOR,  OTP_VERIFIEDBY, DATETIME from (
            SELECT 
                ed.eid, TTID,
                TT.FAULTTYPE, TT.SUBFAULTTYPE,TT.SECTOR   
               ,MAX(CASE WHEN pc.key = 'OTP VERIFICATION' THEN pc.OPERATOR END) AS OTP_VERIFIEDBY,
               max(ed.datetime) as datetime
               FROM ntlcrm.etickets e
               JOIN ntlcrm.eticketdetail ed ON e.id = ed.eid 
               join form_actions pc on pc.eid = e.id
               JOIN installed_hardware hd on e.id = hd.EFORM_ID
               join ntlcrm.troubleticket tt on  tt.id = e.ttid
               WHERE e.status = 'Form_Created' AND ed.status = 'Form_Created' 
               and hd.status = 'Form_Created' 
               GROUP BY  ed.eid,e.ttid, ed.status,
               TTID,
               TT.FAULTTYPE, TT.SUBFAULTTYPE,TT.SECTOR
              ))    
             WHERE DATETIME >= TO_DATE('".strtoupper($FromDate)." 00:00:00', 'DD-MON-YYYY HH24:MI:SS')
               AND DATETIME <= TO_DATE('".strtoupper($ToDate)." 23:59:59', 'DD-MON-YYYY HH24:MI:SS');
               
               
               
               
               SELECT *  FROM (
            SELECT EID, TTID, 
            (SELECT TEAMSHORTTEXT FROM professionalinfo where empid = OTP_VERIFIEDBY) as teamofemployee,
            (SELECT 'Islamabad' FROM professionalinfo where empid = OTP_VERIFIEDBY) as EMP_OFFICECITY,
            (SELECT count(ttid) as totaltt FROM ntlcrm.etickets where OPERATOR = OTP_VERIFIEDBY and status = 'Form_Created') as totaltt,
            SECTOR,  OTP_VERIFIEDBY, DATETIME from (
            SELECT 
                ed.eid, TTID,
                TT.SECTOR   
               ,MAX(CASE WHEN pc.key = 'OTP VERIFICATION' THEN pc.OPERATOR END) AS OTP_VERIFIEDBY,
               max(ed.datetime) as datetime
               FROM ntlcrm.etickets e
               JOIN ntlcrm.eticketdetail ed ON e.id = ed.eid 
               join form_actions pc on pc.eid = e.id
               JOIN installed_hardware hd on e.id = hd.EFORM_ID
               join ntlcrm.troubleticket tt on  tt.id = e.ttid
               WHERE e.status = 'Form_Created' AND ed.status = 'Form_Created' 
               and hd.status = 'Form_Created' 
               GROUP BY  ed.eid,e.ttid, ed.status,
               TTID,
               TT.SECTOR
              ))    
             WHERE DATETIME >= TO_DATE('10-NOV-2023 00:00:00 ', 'DD-MON-YYYY HH24:MI:SS')
               AND DATETIME <= TO_DATE('30-NOV-2023 23:59:59', 'DD-MON-YYYY HH24:MI:SS') and OTP_VERIFIEDBY in (select empid from professionalinfo p inner join deptdesignation d on p.dept_desig_id=d.deptdesigid where d.subdept in ('Installations'));
               
               SELECT DISTINCT AREA AS SECTOR FROM PROFITCENTERS;
                
                SELECT DISTINCT 'ISLAMABAD' FROM PROFITCENTERS WHERE STATUS = 'enabled' and city is not null;
                
                
                SELECT empid FROM professionalinfo a join deptdesignation d on 
        a.DEPT_DESIG_ID = d.DEPTDESIGID where emptype = 'Permanent';
        
               
               SELECT *  FROM (
            SELECT EID, TTID, 
            (SELECT TEAMSHORTTEXT FROM professionalinfo where empid = OTP_VERIFIEDBY) as teamofemployee,
            (SELECT OFFICECITY FROM professionalinfo where empid = OTP_VERIFIEDBY) as EMP_OFFICECITY,
            (SELECT count(ttid) as totaltt FROM ntlcrm.etickets where OPERATOR = OTP_VERIFIEDBY and status = 'Form_Created') as totaltt,
            SECTOR,  OTP_VERIFIEDBY, DATETIME from (
            SELECT 
                ed.eid, TTID,
                TT.SECTOR   
               ,MAX(CASE WHEN pc.key = 'OTP VERIFICATION' THEN pc.OPERATOR END) AS OTP_VERIFIEDBY,
               max(ed.datetime) as datetime
               FROM ntlcrm.etickets e
               JOIN ntlcrm.eticketdetail ed ON e.id = ed.eid 
               join form_actions pc on pc.eid = e.id
               JOIN installed_hardware hd on e.id = hd.EFORM_ID
               join ntlcrm.troubleticket tt on  tt.id = e.ttid
               WHERE e.status = 'Form_Created' AND ed.status = 'Form_Created' 
               and hd.status = 'Form_Created' 
               GROUP BY  ed.eid,e.ttid, ed.status,
               TTID,
               TT.SECTOR
              ))    
             WHERE DATETIME >= TO_DATE('01-NOV-2023 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
               AND DATETIME <= TO_DATE('01-DEC-2023 23:59:59', 'DD-MM-YYYY HH24:MI:SS')
               and OTP_VERIFIEDBY in (select empid from professionalinfo p inner join deptdesignation d on p.dept_desig_id=d.deptdesigid where d.subdept in ('Installations'));
          
          
    SELECT
        *
    FROM ntlcrm.troubleticket;     
          
               
--  i have a table professionalinfo and deptdesignation, professionalinfo has empid and dept_desig_id while deptdesignation has deptdesigid, now you have to make a condition where you have to display empid by making join as OTP_VERIFYBY
  
               
select distinct b.id,eid,key,sub_key,value,sub_value ,rate, INPACKAGE_QUANTITY, IN_PREMISES, OUT_PREMISES, AMOUNT,QUANTITY, m.MATERIALNUMBER
from ntlcrm.etickets a join ntlcrm.eticketdetail b on a.id = b.eid and key = 'MATERIAL' 

JOIN MATERIAL_COST_SAP m ON b.VALUE = m.MATERIALDESCRIPTION;


select distinct b.id,eid,key,sub_key,value,sub_value ,rate, 
        INPACKAGE_QUANTITY, IN_PREMISES, OUT_PREMISES, AMOUNT,QUANTITY, m.MATERIALNUMBER  from  ntlcrm.etickets a 
        join ntlcrm.eticketdetail b on a.id = b.eid and key = 'MATERIAL' 
        JOIN MATERIAL_COST_SAP m ON b.VALUE = m.MATERIALDESCRIPTION
        where a.id =10288;
        
SELECT *  FROM (
            SELECT EID, TTID, 
            (SELECT TEAMSHORTTEXT FROM professionalinfo where empid = OTP_VERIFIEDBY) as teamofemployee,
            (SELECT OFFICECITY FROM professionalinfo where empid = OTP_VERIFIEDBY) as EMP_OFFICECITY,
            (SELECT count(ttid) as totaltt FROM ntlcrm.etickets where OPERATOR = OTP_VERIFIEDBY and status = 'Form_Created') as totaltt,
            SECTOR,  OTP_VERIFIEDBY, DATETIME from (
            SELECT 
                ed.eid, TTID,
                TT.SECTOR   
               ,MAX(CASE WHEN pc.key = 'OTP VERIFICATION' THEN pc.OPERATOR END) AS OTP_VERIFIEDBY,
               max(ed.datetime) as datetime
               FROM ntlcrm.etickets e
               JOIN ntlcrm.eticketdetail ed ON e.id = ed.eid 
               join form_actions pc on pc.eid = e.id
               JOIN installed_hardware hd on e.id = hd.EFORM_ID
               join ntlcrm.troubleticket tt on  tt.id = e.ttid
               WHERE e.status = 'Form_Created' AND ed.status = 'Form_Created' 
               and hd.status = 'Form_Created' 
               GROUP BY  ed.eid,e.ttid, ed.status,
               TTID,
               TT.SECTOR
              ))    
             WHERE DATETIME >= TO_DATE('04-NOV-2023 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
               AND DATETIME <= TO_DATE('04-DEC-2023 23:59:59', 'DD-MM-YYYY HH24:MI:SS')
    and OTP_VERIFIEDBY in (select empid from professionalinfo p inner join deptdesignation d on p.dept_desig_id=d.deptdesigid where d.subdept in ('Complaints')); 
    
    
select * from ntlcrm.eticketdetail where EID='9121' and key='MATERIAL' and status='Form_Created';

SELECT * FROM professionalinfo;
SELECT * FROM deptdesignation;
SELECT distinct operator_department FROM form_actions order by id desc;


SELECT DISTINCT operator_department, id
FROM form_actions where operator_department='Transmission' 
ORDER BY id DESC;


    SELECT empid FROM professionalinfo a join deptdesignation d on 
        a.DEPT_DESIG_ID = d.DEPTDESIGID where subdept = 'Installations';
